# Fly.io deployment configuration for weed diversity analyzer
app = "weed-diversity-analyzer"
primary_region = "nrt"  # Tokyo region for Japan

[build]

[env]
  PORT = "8000"
  LOG_LEVEL = "INFO"
  PYTHONUNBUFFERED = "1"
  PRODUCTION = "true"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "30s"
  grace_period = "10s"
  method = "GET"
  path = "/health"
  protocol = "http"
  timeout = "5s"
  tls_skip_verify = false

[machine]
  memory = "4gb"
  cpu_kind = "shared"
  cpus = 2

# [[mounts]]
#   source = "weed_data"
#   destination = "/app/data"

# [[mounts]]
#   source = "weed_output"
#   destination = "/app/output"

# [deploy]
#   release_command = "python -c 'from src.database.migrate import run_migrations; run_migrations()'"
