
app:
  name: "Weed Diversity Analyzer"
  version: "1.0.0"
  debug: false
  log_level: "INFO"

paths:
  data_root: "data"
  raw_data: "data/raw"
  processed_data: "data/processed"
  models: "data/models"
  output: "output"
  logs: "logs"
  temp: "temp"

preprocessing:
  image_size: [224, 224]
  
  min_resolution: [512, 512]
  max_file_size_mb: 50
  
  clahe:
    enabled: true
    clip_limit: 2.0
    tile_grid_size: [8, 8]
  
  white_balance:
    enabled: true
    method: "gray_world"  # Options: gray_world, white_patch, learning_based
  
  gamma_correction:
    enabled: true
    gamma_range: [0.8, 1.2]
  
  similarity:
    method: "ssim"  # Options: ssim, feature_based, histogram
    threshold: 0.85
    clustering_method: "kmeans"  # Options: kmeans, hierarchical
    max_clusters: 10

models:
  primary:
    name: "weednet"
    model_path: "data/models/weednet.pth"
    confidence_threshold: 0.5
    top_k: 3
    
  fallback:
    - name: "inatag"
      model_path: "data/models/inatag.pth"
      confidence_threshold: 0.4
    - name: "agrinet"
      model_path: "data/models/agrinet.pth"
      confidence_threshold: 0.4
    - name: "deepweeds"
      model_path: "data/models/deepweeds.pth"
      confidence_threshold: 0.3
  
  inference:
    batch_size: 16
    device: "auto"  # Options: auto, cpu, cuda
    num_workers: 4
    use_amp: true  # Automatic Mixed Precision

classification:
  confidence_thresholds:
    species: 0.7
    genus: 0.5
    family: 0.3
  
  soft_voting:
    enabled: true
    weights: [0.6, 0.3, 0.1]  # Weights for top-3 predictions
  
  unknown_threshold: 0.2

diversity:
  indices:
    - "richness"
    - "shannon"
    - "pielou"
    - "simpson"
    - "hill_q0"
    - "hill_q1"
    - "hill_q2"
  
  estimators:
    chao1:
      enabled: true
      confidence_level: 0.95
    
    coverage_standardization:
      enabled: true
      target_coverage: 0.8
      max_iterations: 1000
  
  subsampling:
    enabled: true
    method: "rarefaction"  # Options: rarefaction, bootstrap
    target_size: 30
    iterations: 1000
    confidence_level: 0.95
  
  bootstrap:
    enabled: true
    iterations: 1000
    confidence_level: 0.95
    method: "percentile"  # Options: percentile, bca

output:
  daily_summary:
    include_confidence_intervals: true
    include_top_species: 10
    include_metadata: true
  
  detailed_csv:
    include_all_predictions: true
    include_image_metadata: true
    include_processing_info: true
  
  visualization:
    calendar_format: "github_grass"
    time_series_format: "plotly_json"
    include_interactive: true

processing:
  max_workers: 4
  chunk_size: 100
  
  max_memory_gb: 8
  clear_cache_interval: 1000
  
  progress_bar: true
  log_interval: 100

quality_control:
  blur_detection:
    enabled: true
    threshold: 100
  
  exposure_check:
    enabled: true
    underexposed_threshold: 0.1
    overexposed_threshold: 0.9
  
  prediction_consistency:
    enabled: true
    min_agreement: 0.6
  
  outlier_detection:
    enabled: true
    method: "isolation_forest"
    contamination: 0.1

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_rotation: true
  max_file_size_mb: 100
  backup_count: 5
  
  components:
    preprocessing: "INFO"
    models: "INFO"
    analysis: "INFO"
    output: "INFO"

development:
  test_data_size: 100
  mock_models: false
  
  save_intermediate_results: false
  profile_performance: false
  
  cross_validation:
    enabled: false
    folds: 5
    stratified: true
